[project]
name = "AsciiArt"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.11"

[dependency-groups]
dev = ["boto3>=1.34.119", "pytest>=8.0.0", "requests>=2.32.3"]
lint = ["ruff>=0.10.0", "pylint"]
downsize_media = []
downsize_video = []
extract_audio = []
merge_frames = []
process_frames = []
process_image = []

[tool.ruff]
line-length = 90
target-version = "py311"
indent-width = 4

exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".pyenv",
  ".ruff_cache",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "build",
  "dist",
  "site-packages",
  "venv",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D107",
  "D206",
  "E501",
  "G004",
  "TC002",
  "TC003",
  "TD002",
  "TD003",
  "LOG015",
  "TRY300",
  "TRY301",
  "INP001",
]
fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.uv.pip]
python-version = "3.11"

[tool.pylint]
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "invalid-name",
  "too-few-public-methods",
  "too-many-arguments",
  "too-many-locals",
  "too-many-statements",
  "logging-fstring-interpolation",
  # "import-error",
]
ignore-patterns = ["**/site-packages/**/*.py", ".vscode/*.py"]

[tool.pylint.messages_control]
convention = "Hint"
error = "Error"
fatal = "Error"
refactor = "Hint"
warning = "Warning"
info = "Information"


[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
check_untyped_defs = true
# disallow_untyped_defs = true
# disallow_incomplete_defs = true
# ignore_missing_imports = true
exclude = '''
/(
    \.git
    | \.venv
    | build
    | dist
)/
'''

[tool.basedpyright]
exclude = [
  "**/node_modules",
  "**/__pycache__",
  ".venv",
]
venvPath = "."
venv = ".venv"

reportMissingImports = "error"
reportMissingTypeStubs = "warning"
reportUnusedImport = "warning"
typeCheckingMode = "strict"
