[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311", "py312"]
exclude = '''
/(
    \.git
    | \.mypy_cache
    | \.ruff_cache
    | \.venv
    | build
    | dist
)/
'''

[tool.ruff]
line-length = 88
target-version = "py310"
select = ["E", "F", "W", "B", "I"]
ignore = ["E501"]  # Ignore line-length checks if handled by Black
extend-exclude = [
    "build/",
    "dist/",
    ".venv/",
    ".ruff_cache/",
    ".mypy_cache/",
]
fixable = ["ALL"]  # Enable Ruff's autofix capabilities

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
ignore_missing_imports = true
exclude = '''
/(
    \.git
    | \.venv
    | build
    | dist
)/
'''

[tool.pyright]
include = ["lambdas"]
exclude = ["**/node_modules",
    "**/__pycache__"
]
defineConstant = { DEBUG = true }

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.12"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = ".venv", pythonVersion = "3.12", pythonPlatform = "Linux", reportMissingImports = "warning" }
]
