[tool.pyright]
include = ["lambdas"]
exclude = ["**/node_modules",
    "**/__pycache__"
]
defineConstant = { DEBUG = true }

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.12"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = ".venv", pythonVersion = "3.12", pythonPlatform = "Linux", reportMissingImports = "warning" }
]
